name: tran_gia_app
description: "Tran Gia Food Monorepo Root"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.12.2'

workspace:
  - apps/customer_app
  - apps/restaurant_app
  - apps/shipper_app
  - packages/shared_models
  - packages/shared_ui
  - packages/api_client

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^6.0.0
