name: shared_models
description: Shared Dart models, enums, and DTOs for Tran Gia Food apps
version: 0.0.1
publish_to: none

resolution: workspace

environment:
  sdk: '^3.12.2'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  freezed: ^3.2.6-dev.1
  json_serializable: ^6.7.1
